<template>
  <div class="container mt-4">
    <h2>Add New Facility</h2>

    <div v-if="loading" class="alert alert-info">Submitting...</div>
    <div v-if="error" class="alert alert-danger">{{ error }}</div>
    <div v-if="successMessage" class="alert alert-success">{{ successMessage }}</div>

    <form id="newFacilityForm" @submit.prevent="handleFormSubmit">
      <!-- Basic Info Section -->
      <fieldset class="mb-3">
        <legend>Basic Information</legend>
        <div class="mb-3">
          <label for="facilityName" class="form-label">Facility Name</label>
          <input type="text" class="form-control" id="facilityName" v-model="formData.name" required>
        </div>
        <!-- ID is usually generated by the backend, so it's not included here -->
        <div class="mb-3">
          <label for="company" class="form-label">Company</label>
          <input type="text" class="form-control" id="company" v-model="formData.company">
        </div>
        <div class="mb-3">
          <label for="status" class="form-label">Status</label>
          <select class="form-select" id="status" v-model="formData.status" required>
            <option>Operating</option>
            <option>Under Construction</option>
            <option>Planned</option>
            <option>Closed</option>
            <option>On Hold</option>
          </select>
        </div>
        <div class="mb-3">
          <label for="address" class="form-label">Address</label>
          <input type="text" class="form-control" id="address" v-model="formData.address">
        </div>
        <div class="mb-3">
          <label for="region" class="form-label">Region/State</label>
          <input type="text" class="form-control" id="region" v-model="formData.region">
        </div>
        <div class="mb-3">
          <label for="country" class="form-label">Country</label>
          <input type="text" class="form-control" id="country" v-model="formData.country">
        </div>
      </fieldset>

      <!-- Location Section -->
      <fieldset class="mb-3">
        <legend>Location (Coordinates)</legend>
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="longitude" class="form-label">Longitude</label>
            <input type="number" step="any" class="form-control" id="longitude" v-model.number="formData.longitude" required>
          </div>
          <div class="col-md-6 mb-3">
            <label for="latitude" class="form-label">Latitude</label>
            <input type="number" step="any" class="form-control" id="latitude" v-model.number="formData.latitude" required>
          </div>
        </div>
      </fieldset>

      <!-- Technical Details Section -->
      <fieldset class="mb-3">
        <legend>Technical Details</legend>
        <div class="mb-3">
          <label for="capacity" class="form-label">Capacity (Tonnes/Year)</label>
          <input type="text" class="form-control" id="capacity" v-model="formData.capacity">
        </div>
        <div class="mb-3">
          <label for="technology" class="form-label">Technology</label>
          <input type="text" class="form-control" id="technology" v-model="formData.technology">
        </div>
        <div class="mb-3">
          <label for="yearStarted" class="form-label">Year Started / Planned</label>
          <input type="number" class="form-control" id="yearStarted" v-model.number="formData.yearStarted">
           <small class="form-text text-muted">Enter the year the facility started operating or is planned to start.</small>
        </div>
         <div class="mb-3">
          <label for="size" class="form-label">Size (e.g., sq ft, sq m)</label>
          <input type="text" class="form-control" id="size" v-model="formData.size">
        </div>
        <div class="mb-3">
          <label for="feedstock" class="form-label">Feedstock</label>
          <textarea class="form-control" id="feedstock" rows="3" v-model="formData.feedstock"></textarea>
        </div>
        <div class="mb-3">
          <label for="products" class="form-label">Products</label>
          <textarea class="form-control" id="products" rows="3" v-model="formData.products"></textarea>
        </div>
         <div class="mb-3">
          <label for="technologyDetails" class="form-label">Technology Details</label>
          <textarea class="form-control" id="technologyDetails" rows="4" v-model="formData.technologyDetails"></textarea>
        </div>
      </fieldset>

      <!-- Description &amp; Media Section -->
      <fieldset class="mb-3">
        <legend>Description &amp; Media</legend>
        <div class="mb-3">
          <label for="description" class="form-label">Description</label>
          <textarea class="form-control" id="description" rows="5" v-model="formData.description"></textarea>
        </div>
        <div class="mb-3">
          <label for="website" class="form-label">Website URL</label>
          <input type="url" class="form-control" id="website" v-model="formData.website">
        </div>
        <div class="mb-3">
          <label for="companyLogo" class="form-label">Company Logo URL</label>
          <input type="url" class="form-control" id="companyLogo" v-model="formData.companyLogo">
        </div>
        <div class="mb-3">
          <label for="facilityImage" class="form-label">Facility Image URL</label>
          <input type="url" class="form-control" id="facilityImage" v-model="formData.facilityImage">
        </div>
         <div class="mb-3">
          <label for="fundingSource" class="form-label">Funding Source</label>
          <input type="text" class="form-control" id="fundingSource" v-model="formData.fundingSource">
        </div>
      </fieldset>

       <!-- Timeline Section -->
      <fieldset class="mb-3">
        <legend>Timeline (JSON Array)</legend>
        <div class="mb-3">
          <label for="timeline" class="form-label">Timeline Events</label>
          <textarea class="form-control" id="timeline" rows="6" v-model="timelineJson" placeholder='[
  { "date": "YYYY-MM-DD", "event": "Event description" },
  { "date": "YYYY-MM-DD", "event": "Another event" }
]'></textarea>
          <small class="form-text text-muted">Enter a valid JSON array of timeline objects, each with 'date' and 'event' keys.</small>
           <div v-if="timelineError" class="alert alert-danger mt-2">{{ timelineError }}</div>
        </div>
      </fieldset>

      <!-- Action Buttons -->
      <div class="d-flex justify-content-start align-items-center">
        <button type="submit" class="btn btn-success me-2" :disabled="loading || !!timelineError">Create Facility</button>
        <button type="button" class="btn btn-secondary" @click="cancelCreate">Cancel</button>
      </div>
    </form>
  </div>
</template>

<script setup>
import { ref, watch } from 'vue';
import { useRouter } from 'vue-router';
import { useFacilityStore } from '@/stores/facilityStore';

const router = useRouter();
const facilityStore = useFacilityStore();

// Initialize form data with default values
const formData = ref({
  name: '',
  company: '',
  status: 'Planned', // Default status
  address: '',
  region: '',
  country: '',
  longitude: null,
  latitude: null,
  capacity: '',
  technology: '',
  yearStarted: null, // Will be handled based on status
  size: '',
  feedstock: '',
  products: '',
  technologyDetails: '',
  description: '',
  website: '',
  companyLogo: '',
  facilityImage: '',
  fundingSource: '',
  // documents: [], // Documents are usually added/managed separately
  // timeline: [] // Handled by timelineJson
});

const loading = ref(false);
const error = ref('');
const successMessage = ref('');
const timelineJson = ref('[]'); // Store timeline as JSON string
const timelineError = ref(''); // Error specific to timeline JSON parsing

// Function to safely parse timeline JSON
const parseTimeline = (jsonString) => {
  try {
    const parsed = JSON.parse(jsonString || '[]');
    if (!Array.isArray(parsed)) {
      throw new Error("Timeline must be a valid JSON array.");
    }
    // Optional: Validate structure of array items
    parsed.forEach(item => {
        if (typeof item !== 'object' || item === null || !item.date || !item.event) {
            throw new Error("Each timeline item must be an object with 'date' and 'event' properties.");
        }
    });
    timelineError.value = ''; // Clear error if valid
    return parsed;
  } catch (e) {
    timelineError.value = `Invalid Timeline JSON: ${e.message}`;
    return null; // Indicate parsing failure
  }
};

// Watch for changes in the timeline textarea and validate
watch(timelineJson, (newJson) => {
  parseTimeline(newJson); // Validate on change
});

const handleFormSubmit = async () => {
  if (timelineError.value) {
      error.value = "Please fix the errors in the Timeline JSON before saving.";
      successMessage.value = '';
      return; // Prevent submission if timeline JSON is invalid
  }

  loading.value = true;
  error.value = '';
  successMessage.value = '';

  const parsedTimeline = parseTimeline(timelineJson.value);
   if (parsedTimeline === null) {
      error.value = "Timeline JSON is invalid.";
      loading.value = false;
      return;
  }

  // Prepare data for creation (properties and geometry)
  const newFacilityData = {
      properties: {
          ...formData.value,
          // Remove coordinates from properties
          longitude: undefined,
          latitude: undefined,
          // Handle yearStarted/yearPlanned based on status
          yearStarted: formData.value.status !== 'Planned' ? formData.value.yearStarted || undefined : undefined,
          yearPlanned: formData.value.status === 'Planned' ? formData.value.yearStarted || undefined : undefined,
          // Add parsed timeline
          timeline: parsedTimeline.length > 0 ? parsedTimeline : undefined,
          // Initialize documents as empty array
          documents: []
      },
      geometry: {
          type: "Point",
          coordinates: [
              formData.value.longitude,
              formData.value.latitude
          ]
      }
  };

   // Clean up undefined/null/empty properties before sending
   Object.keys(newFacilityData.properties).forEach(key => {
       if (newFacilityData.properties[key] === undefined || newFacilityData.properties[key] === null || newFacilityData.properties[key] === '') {
           delete newFacilityData.properties[key];
       }
   });
    // Ensure timeline is at least an empty array if cleared
   if (!newFacilityData.properties.timeline) newFacilityData.properties.timeline = [];


  try {
    // Call the store action to create the facility
    const createdFacility = await facilityStore.createFacility(newFacilityData);
    successMessage.value = `Facility "${createdFacility.properties.name}" created successfully! Redirecting...`;

    // Redirect to the new facility's detail page or the list page
    setTimeout(() => {
      if (createdFacility && createdFacility.properties.id) {
         router.push({ name: 'FacilityDetail', params: { id: createdFacility.properties.id } });
      } else {
         router.push({ name: 'FacilitiesList' }); // Fallback to list
      }
    }, 2000);
  } catch (err) {
    console.error('Error creating facility:', err);
    error.value = `Failed to create facility: ${err.message || 'Unknown error'}`;
  } finally {
    loading.value = false;
  }
};

const cancelCreate = () => {
  // Navigate back to the facilities list page
  router.push({ name: 'FacilitiesList' });
};

</script>

<style scoped>
/* Add any component-specific styles here */
fieldset {
  border: 1px solid #ccc;
  padding: 1.5rem;
  border-radius: 0.25rem;
}
legend {
  width: auto;
  padding: 0 0.5rem;
  font-size: 1.2rem;
  font-weight: bold;
}
</style>